#!/bin/bash

### YouTube downloads ###

# MOVED TO YT-DLP FOLLOWING ISSUE #31530 - https://github.com/ytdl-org/youtube-dl/issues/31530

YOUTUBE_DL=$SNAP_COMMON/podcast-dl/bin/youtube-dl

# Download or update yt-dlp to the latest version

if [[ ! -f "$YOUTUBE_DL" ]]; then

   curl --silent --location https://github.com/yt-dlp/yt-dlp/releases/download/2024.12.06/yt-dlp --output "$YOUTUBE_DL"
   chmod a+rx "$YOUTUBE_DL"
fi

"$YOUTUBE_DL" --update-to stable

# --config-location PATH    Location of the configuration file; either the path to the config or its containing directory.

"$YOUTUBE_DL" --config-location $SNAP_COMMON/podcast-dl/youtube-dl.conf.d/youtube-dl.conf
