#!/bin/bash

### YouTube downloads ###

# Update youtube-dl to the latest version

curl --silent --location https://yt-dl.org/downloads/latest/youtube-dl --output $SNAP_COMMON/podcast-dl/bin/youtube-dl
chmod a+rx $SNAP_COMMON/podcast-dl/bin/youtube-dl

# --config-location PATH    Location of the configuration file; either the path to the config or its containing directory.
# --dateafter DATE          Download only videos uploaded on or after this date (i.e. inclusive)

$SNAP_COMMON/podcast-dl/bin/youtube-dl --config-location $SNAP_COMMON/podcast-dl/youtube-dl.conf.d/youtube-dl.conf
