#!/bin/bash

### YouTube downloads ###

# MOVED TO YT-DLP FOLLOWING ISSUE #31530 - https://github.com/ytdl-org/youtube-dl/issues/31530

YOUTUBE_DL=$SNAP_COMMON/podcast-dl/bin/youtube-dl

# Update yt-dlp to the latest version

"$YOUTUBE_DL" --update-to stable

# --config-location PATH    Location of the configuration file; either the path to the config or its containing directory.

"$YOUTUBE_DL" --config-location $SNAP_COMMON/podcast-dl/youtube-dl.conf.d/youtube-dl.conf
